import type { Post, Course } from './types';
import { Briefcase, Clock, Code, LineChart, DollarSign, BrainCircuit, Tv, Megaphone, Users, Rocket, BarChart } from 'lucide-react';

export const blogPosts: Post[] = [
  // Money & Finance
  {
    slug: 'start-forex-trading-with-10-dollars',
    title: 'How to Start Forex Trading with Just $10',
    category: 'Money & Finance',
    description: 'A beginner-friendly guide to entering the forex market with minimal investment. Learn the basics and make your first trade.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'money chart',
    author: 'Jane Doe',
    authorImage: 'https://picsum.photos/40/40',
    date: '2024-07-28',
  },
  {
    slug: '5-crypto-wallets-for-beginners-2025',
    title: '5 Crypto Wallets Every Beginner Should Use in 2025',
    category: 'Money & Finance',
    description: 'Discover the most secure and user-friendly crypto wallets to start your journey in digital currencies.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'digital wallet',
    author: 'John Smith',
    authorImage: 'https://picsum.photos/40/40',
    date: '2024-07-27',
  },
  {
    slug: 'nigerian-side-hustles-500-monthly',
    title: '10 Side Hustles Nigerians Are Using to Make $500+ Monthly',
    category: 'Money & Finance',
    description: 'Explore popular and effective side hustles that are helping Nigerians achieve their financial goals.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'small business',
    author: 'Alex Johnson',
    authorImage: 'https://picsum.photos/40/40',
    date: '2024-07-26',
  },
  {
    slug: 'earn-passive-income-online',
    title: 'How to Earn Passive Income Online (Even While Sleeping)',
    category: 'Money & Finance',
    description: 'Learn proven strategies to create automated income streams that work for you 24/7.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'laptop beach',
    author: 'Emily White',
    authorImage: 'https://picsum.photos/40/40',
    date: '2024-07-25',
  },
  // Social Media Monetization
  {
    slug: 'create-facebook-business-page',
    title: 'How to Create a Facebook Page for Your Business (Step by Step)',
    category: 'Social Media Monetization',
    description: 'A complete walkthrough on setting up a professional Facebook page to attract customers and grow your brand.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'social media',
    author: 'Jane Doe',
    authorImage: 'https://picsum.photos/40/40',
    date: '2024-07-24',
  },
  {
    slug: 'monetize-youtube-shorts-2025',
    title: 'How to Monetize YouTube Shorts in 2025',
    category: 'Social Media Monetization',
    description: 'Unlock the potential of YouTube Shorts and learn how to turn your short-form content into a revenue source.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'video creator',
    author: 'John Smith',
    authorImage: 'https://picsum.photos/40/40',
    date: '2024-07-23',
  },
  {
    slug: 'tiktok-monetization-trending-sounds',
    title: 'TikTok Monetization: How to Earn from Trending Sounds',
    category: 'Social Media Monetization',
    description: 'Capitalize on viral trends by learning how to use trending sounds to monetize your TikTok presence.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'phone screen',
    author: 'Alex Johnson',
    authorImage: 'https://picsum.photos/40/40',
    date: '2024-07-22',
  },
  {
    slug: 'grow-telegram-channel-get-paid',
    title: 'How to Grow a Telegram Channel and Get Paid',
    category: 'Social Media Monetization',
    description: 'Strategies for building a large and engaged Telegram channel and the different ways to monetize it.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'messaging app',
    author: 'Emily White',
    authorImage: 'https://picsum.photos/40/40',
    date: '2024-07-21',
  },
  // AI & Tech
  {
    slug: 'use-chatgpt-to-make-money',
    title: 'How to Use ChatGPT to Make Money Online',
    category: 'AI & Tech',
    description: 'Practical ways you can leverage ChatGPT to create new income streams and automate tasks.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'artificial intelligence',
    author: 'Jane Doe',
    authorImage: 'https://picsum.photos/40/40',
    date: '2024-07-20',
  },
  {
    slug: '5-ways-ai-can-help-start-side-hustle',
    title: '5 Ways AI Can Help You Start a Side Hustle',
    category: 'AI & Tech',
    description: 'Discover how AI tools can simplify the process of launching and running a successful side business.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'robot assistant',
    author: 'John Smith',
    authorImage: 'https://picsum.photos/40/40',
    date: '2024-07-19',
  },
  {
    slug: 'build-no-code-app-in-1-hour-glide',
    title: 'How to Build a No-Code App in 1 Hour (Glide Tutorial)',
    category: 'AI & Tech',
    description: 'A step-by-step tutorial on using Glide to build a fully functional application without any coding knowledge.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'app development',
    author: 'Alex Johnson',
    authorImage: 'https://picsum.photos/40/40',
    date: '2024-07-18',
  },
  {
    slug: 'create-telegram-bot-without-coding',
    title: 'How to Create a Telegram Bot Without Coding',
    category: 'AI & Tech',
    description: 'Learn how to build and deploy your own Telegram bot using no-code platforms.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'robot chat',
    author: 'Emily White',
    authorImage: 'https://picsum.photos/40/40',
    date: '2024-07-17',
  },
  // Freelancing & Jobs
  {
    slug: 'top-10-fiverr-gigs-with-ai-tools',
    title: 'Top 10 Fiverr Gigs You Can Start With AI Tools',
    category: 'Freelancing & Jobs',
    description: 'Find out the most in-demand Fiverr services you can offer by leveraging powerful AI tools.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'freelance work',
    author: 'Jane Doe',
    authorImage: 'https://picsum.photos/40/40',
    date: '2024-07-16',
  },
  {
    slug: 'start-freelancing-with-zero-experience',
    title: 'How to Start Freelancing with Zero Experience',
    category: 'Freelancing & Jobs',
    description: 'A roadmap for aspiring freelancers on how to land their first client and build a successful career from scratch.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'home office',
    author: 'John Smith',
    authorImage: 'https://picsum.photos/40/40',
    date: '2024-07-15',
  },
  {
    slug: 'upwork-vs-fiverr-2025',
    title: 'Upwork vs Fiverr: Which is Better in 2025?',
    category: 'Freelancing & Jobs',
    description: 'An in-depth comparison of the two leading freelance platforms to help you choose the right one for your skills.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'decision choice',
    author: 'Alex Johnson',
    authorImage: 'https://picsum.photos/40/40',
    date: '2024-07-14',
  },
  {
    slug: 'get-paid-online-payment-gateways',
    title: 'How to Get Paid Online (Payoneer, Binance, Wise, Flutterwave)',
    category: 'Freelancing & Jobs',
    description: 'A guide to the best online payment platforms for freelancers and businesses to receive payments globally.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'online payment',
    author: 'Emily White',
    authorImage: 'https://picsum.photos/40/40',
    date: '2024-07-13',
  },
  // Productivity & Lifestyle
  {
    slug: '7-tools-for-remote-workers-2025',
    title: '7 Tools Every Remote Worker Needs in 2025',
    category: 'Productivity & Lifestyle',
    description: 'Boost your productivity and collaboration with these essential tools for working from anywhere.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'desk setup',
    author: 'Jane Doe',
    authorImage: 'https://picsum.photos/40/40',
    date: '2024-07-12',
  },
  {
    slug: 'time-management-for-side-hustlers',
    title: 'How to Manage Your Time Like a Pro (For Side Hustlers)',
    category: 'Productivity & Lifestyle',
    description: 'Learn effective time management techniques to balance a full-time job with your side hustle.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'calendar planning',
    author: 'John Smith',
    authorImage: 'https://picsum.photos/40/40',
    date: '2024-07-11',
  },
  {
    slug: 'build-personal-brand-online-30-days',
    title: 'How to Build Your Personal Brand Online in 30 Days',
    category: 'Productivity & Lifestyle',
    description: 'A 30-day challenge to help you create a strong and authentic personal brand on social media and beyond.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'personal branding',
    author: 'Alex Johnson',
    authorImage: 'https://picsum.photos/40/40',
    date: '2024-07-10',
  },
  {
    slug: 'best-apps-to-earn-rewards-2025',
    title: 'Best Apps to Earn Rewards from Daily Tasks (2025 list)',
    category: 'Productivity & Lifestyle',
    description: 'A curated list of mobile apps that reward you for completing simple daily tasks, surveys, and more.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'gift card',
    author: 'Emily White',
    authorImage: 'https://picsum.photos/40/40',
    date: '2024-07-09',
  },
];

export const courses: Course[] = [
  {
    slug: 'forex-mastery',
    title: 'Forex Mastery: From Basics to Advanced',
    track: 'Money Skills',
    description: 'A complete course on Forex trading, covering everything from the basics to advanced strategies.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'stock market',
    lessons: 25,
    hours: 10,
    isFeatured: true,
    progress: 0,
  },
  {
    slug: 'ai-prompt-engineering-101',
    title: 'Prompt Engineering 101',
    track: 'AI & Tech Skills',
    description: 'Master the art of crafting effective prompts for AI models like ChatGPT and Gemini.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'artificial intelligence',
    lessons: 15,
    hours: 5,
    progress: 0,
  },
  {
    slug: 'youtube-growth-adsense',
    title: 'YouTube Growth + AdSense',
    track: 'Social Media Growth & Monetization',
    description: 'Learn how to grow your YouTube channel and maximize your AdSense revenue.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'video creator',
    lessons: 30,
    hours: 12,
    progress: 0,
  },
  {
    slug: 'how-to-create-telegram-bot-course',
    title: 'How to create a Telegram bot (practical course)',
    track: 'AI & Tech Skills',
    description: 'A hands-on course that walks you through creating and deploying a functional Telegram bot.',
    image: 'https://picsum.photos/600/400',
    dataAiHint: 'coding bot',
    lessons: 20,
    hours: 8,
    progress: 30,
  }
];

export const topCategories = [
  { name: 'Forex', icon: LineChart },
  { name: 'AI', icon: BrainCircuit },
  { name: 'Social Media', icon: Megaphone },
  { name: 'Online Hustles', icon: Briefcase },
];

export const blogCategories = [
    { name: 'Money & Finance', icon: DollarSign, slug: 'money-finance' },
    { name: 'Social Media Monetization', icon: Tv, slug: 'social-media-monetization' },
    { name: 'AI & Tech', icon: Code, slug: 'ai-tech' },
    { name: 'Freelancing & Jobs', icon: Briefcase, slug: 'freelancing-jobs' },
    { name: 'Productivity & Lifestyle', icon: Clock, slug: 'productivity-lifestyle' },
];

export const courseTracks = [
    { name: 'Money Skills', icon: BarChart, slug: 'money-skills' },
    { name: 'AI & Tech Skills', icon: Rocket, slug: 'ai-tech-skills' },
    { name: 'Social Media Growth & Monetization', icon: Users, slug: 'social-media-growth' },
]
