[build]
  command = "npm run build"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "GEMINI_API_KEY"
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
