
'use client';

import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export default function TermsOfUsePage() {
  const [lastUpdated, setLastUpdated] = useState('');

  useEffect(() => {
    // Set date on client to avoid hydration mismatch
    setLastUpdated(new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }));
  }, []);

  return (
    <div className="container max-w-4xl py-12 md:py-24">
      <Card>
        <CardHeader>
          <CardTitle className="text-4xl font-bold tracking-tighter sm:text-5xl font-headline">
            Terms of Use
          </CardTitle>
           <p className="text-muted-foreground pt-2">Last Updated: {lastUpdated || '...'}</p>
        </CardHeader>
        <CardContent>
          <div className="prose prose-lg dark:prose-invert max-w-none space-y-4">
            <p>
              Please read these Terms of Use ("Terms", "Terms of Use") carefully before using the BoomerHub website (the "Service") operated by BoomerHub ("us", "we", or "our").
            </p>
            <p>
                Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service. By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.
            </p>

            <h2>1. Intellectual Property</h2>
            <p>
             The Service and its original content (excluding content provided by users), features, and functionality are and will remain the exclusive property of BoomerHub and its licensors. The content on this website, including articles, graphics, and logos, is protected by copyright and other intellectual property laws.
            </p>
            
            <h2>2. Use of AI-Powered Tools</h2>
            <p>
                Our Service includes AI-powered tools ("AI Tools") designed for informational purposes. The advice and analysis provided by these tools (including the AI Financial Adviser and AI Match Prediction) are generated by artificial intelligence and are not a substitute for professional advice.
            </p>
            <ul>
                <li>You are responsible for the inputs you provide to the AI Tools. Do not submit sensitive personal information that you do not want processed by us or our AI service provider (Google AI).</li>
                <li>The outputs from these tools are for informational purposes only. We make no warranties about the accuracy, completeness, or reliability of the information provided.</li>
                <li>Any actions you take based on the information from our AI Tools are at your own risk. For financial matters, you should consult with a qualified professional. For betting, please gamble responsibly.</li>
            </ul>

            <h2>3. Acceptable Use and Rate Limiting</h2>
            <p>
              You agree not to use the Service for any purpose that is illegal or prohibited by these Terms. To ensure fair access and prevent abuse, your use of the AI Tools is subject to a rate limit. We reserve the right to block access from any user or IP address that attempts to circumvent these limits or otherwise abuses the Service. You agree not to:
            </p>
             <ul>
                <li>Use any automated script or bot to access or use the AI tools in a way that exceeds the defined rate limits.</li>
                <li>Harass, abuse, or harm another person.</li>
                <li>Use the Service to transmit any content that is unlawful, fraudulent, or obscene.</li>
                <li>Attempt to gain unauthorized access to the Service or its related systems or networks.</li>
            </ul>

            <h2>4. Disclaimers and Limitation of Liability</h2>
            <p>
             The content on our website and the output of our AI tools are provided on an "as is" and "as available" basis. BoomerHub makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties. Further, BoomerHub does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its website or otherwise relating to such materials or on any sites linked to this site.
            </p>
            <p>In no event shall BoomerHub or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on BoomerHub's website, even if BoomerHub or a BoomerHub authorized representative has been notified orally or in writing of the possibility of such damage.</p>

            <h2>5. Changes to Terms</h2>
            <p>
             We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms of Use on this page. Your continued use of the Service after any such changes constitutes your acceptance of the new Terms of Use.
            </p>
            
             <h2>6. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us through our <a href="/contact">contact page</a>.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
